AllCops:
  Exclude:
    - "bin/*"
    - "db/**/*"
    - "config/**/*"
    - "Guardfile"
    - "Rakefile"
  DisplayCopNames: true
  NewCops: enable

Metrics/MethodLength:
  Include: ["app/controllers/*"]
  Max: 20

Metrics/AbcSize:
  Include: ["app/controllers/*"]
  Max: 30

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  ExcludedMethods: ['describe']

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/ExtraSpacing:
  AllowForAlignment: false

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented